dist: trusty
sudo: false
language: r
cache: packages

env:
  global:
    - secure: "NXIZ5FxxPpXgbgVy5HLQERszLC0g4jnZ94vRwHOne57nVEoaMHVDDgT8c1SzzFPUSBcr/9iaCYJhPeU/RpwXnkrP0GN1kBf5wdC9xkgYNo+JtUWQBhSv+NGH2s+Y+CyyCNPM+opfo3YklZ0w8cDH43atKL2ycK69Fb9tZ9r0f/U="
    - _R_CHECK_TESTS_NLINES_=999
    - _R_CHECK_LENGTH_1_CONDITION_=true

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - if [[ "${TRAVIS_R_VERSION_STRING}" == "release" ]]; then Rscript -e 'covr::coveralls()'; fi
